# Generated by Django 3.2.16 on 2022-11-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExemplosWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='setor',
            field=models.CharField(help_text='Entre o setor', max_length=100, null=True),
        ),
    ]
