# Generated by Django 2.2.4 on 2022-10-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='website',
            field=models.URLField(help_text='Entre com uma URL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(help_text='Entre com a idade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(help_text='Entre com o nome', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='salario',
            field=models.DecimalField(decimal_places=2, help_text='Entre com o salário', max_digits=8),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(help_text='(com DDD e DDI)', max_length=20),
        ),
    ]
