# Generated by Django 2.2.4 on 2022-10-31 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_pessoa_website'),
        ('contatos', '0002_auto_20221010_2146'),
    ]

    operations = [
    ]
